version: '3.7'

services:

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    working_dir: /var/www
    restart: always
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - default
      - internal
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.two.rule=Host(`two.docker.localhost`)'
      - 'traefik.http.services.two.loadbalancer.server.port=80'

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_UID: 1000
        USER_NAME: dockeruser
    working_dir: /var/www
    restart: always
    volumes:
      - .:/var/www
    networks:
      - internal

networks:
  default:
    name: traefik_network
    external: true
  internal:
    name: two
    internal: true
