version: '3.7'

services:

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    working_dir: /var/www
    restart: always
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - default
      - internal
    # https://doc.traefik.io/traefik/routing/providers/docker/#configuration-examples
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.one.rule=Host(`one.docker.localhost`)'
      - 'traefik.http.services.one.loadbalancer.server.port=80'

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        USER_UID: 1000
        USER_NAME: dockeruser
    working_dir: /var/www
    restart: always
    volumes:
      - .:/var/www
    networks:
      - internal

networks:
  default: # внешняя сеть
    name: traefik_network
    external: true
  internal: # внутренняя сеть
    name: one
    internal: true
